apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qotmwn0wm-nodejs 
  janus-idp.io/tekton: qotmwn0wm-nodejs
  backstage.io/kubernetes-id: qotmwn0wm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qotmwn0wm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  