apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qotmwn0wm-nodejs-gitops
  description: This is GitOps manifest for qotmwn0wm-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: qotmwn0wm-nodejs
    backstage.io/kubernetes-id: qotmwn0wm-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qotmwn0wm-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qotmwn0wm-nodejs
